### PR TITLE
Added Circle class

### PR DESCRIPTION
**Pull request by dipakbari4**
Added Circle class to calculate and manipulate about Circle

### CODE REVIEW

**Review by dipakbari4 — COMMENTED** [review]
Default constructor has given default values to initiate and prevent null pointer exception

**Review by dipakbari4 — COMMENTED** [review]
Added default values to default constructor

**Review by dipakbari4 — COMMENTED** [review]
Prototype of Circle class

**Comment by rohanbari** [comment]
@dipakbari4 I'll add some other Circular properties in the next commit.

**Pull request merged**
